server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://discovery-service:8081/eureka'
    enabled: true
  instance:
    preferIpAddress: true

  #  cloud:
#    gateway:
#      routes:
#        - id: auth
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - name: jwtAuthFilter
#        - id: portfolio
#          uri: lb://portfolio-service
#          predicates:
#            - Path=/portfolio/**
#          filters:
#            - name: jwtAuthFilter
#        - id: performance
#          uri: lb://performance-service
#          predicates:
#            - Path=/performance/**
#          filters:
#            - name: jwtAuthFilter
