version: '3.8'
services:
  postgres:
    container_name: 'postgres_15.4'
    build:
      context: services/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_DB=invest_api
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - "db-data:/C/Users/postgres/docker_data"
    restart: unless-stopped
  
  portfolio-service-container:
    container_name: portfolio-service-container
    build:
      context: services/app/portfolio_service
      dockerfile: Dockerfile
    environment:
      - PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_15.4/invest_api
    image: 'portfolio-service-image'
    ports:
      - 8082:8082
    depends_on:
      - postgres
        
volumes:
   db-data: