server:
  port: 8081
  servlet:
    context-path: /api
jwt:
  secret  : ${JWT_SECRET}
  lifetime: 30m
spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    url               : jdbc:postgresql://localhost:5433/invest_api
    username          : ${SPRING_DATASOURCE_USERNAME}
    password          : ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none