server:
  port: 8080
  servlet:
    context-path: /api
jwt:
  secret  : 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    url               : jdbc:postgresql://localhost:5433/invest_api
    username          : ${SPRING_DATASOURCE_USERNAME}
    password          : ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true