server:
  port: 8084
  servlet:
    context-path: /performance

spring:
  application:
    name: performance-service

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://discovery-service:8081/eureka'
    enabled: true